### ISSUE TITLE
SFDX installation fails after 4/24 commit (d42fcad)

### ISSUE THREAD

**Issue by brotheramai** [Kathy-Lueckeman/EASY-Open-Source-Solution#10]
Installing via sfdx (cumulusci) after the 4/24 commit fails with the following errors.

Error:
"Update of RecordType Opportunity.Applicant_Opportunity: Error on
line 289, col 18: Picklist value: New Customer in picklist: Type not found

Update of RecordType Opportunity.Inquiry_Opportunity: Error on line 348, col 18: Picklist value: New Customer
in picklist: Type not found"

Underlying Problem:
The 'New Customer' Opportunity Type that is referenced by /src/objects/Opportunity.object does not exist in /unpackaged/pre/opportunity_types/standardValueSets/OpportunityType.standardValueSet. 

Error:
"Update of Layout Opportunity-Inquiry Opportunity: Error on line 18, col 26: In field: field - no CustomField named Opportunity.Last_Campaign_Source__c found

Update of Layout Opportunity-Applicant Opportunity: Error on line 18, col 26: In field: field - no CustomField named Opportunity.Last_Campaign_Source__c found?"

Underlying Problem:
Last_Campaign_Source__c was removed from /src/objects/Opportunity.object but was not removed from /src/layouts/Opportunity-Inquiry Opportunity.layout and /src/layouts/Opportunity-Applicant Opportunity.layout.

**Comment by kyleschmid** [comment]
@nicolas-scarrci Thanks for logging. I just uploaded a new version without those pieces included. Let me know if you have any issues with this one.

**Comment by brotheramai** [comment]
That did it! Thanks @kyleschmid!
