### ISSUE TITLE
cumulus.yml api_version does not match metadata

### ISSUE THREAD

**Issue by brotheramai** [Kathy-Lueckeman/EASY-Open-Source-Solution#13]
When trying to install via cumulusci the following error message is reported for each custom object
"[Failed]: Update of CustomObject Academic_Term__c: Error: Property 'enableLicensing' not valid in version 38.0"

I believe this is because the metadata in the project is actually pulled with api version 45, but the cumulus.yml file specifies api_version: '38.0' (as does src/package.xml)

**Comment by brotheramai** [comment]
**Workaround** for anyone else deploying EASY to scratch orgs you can perform the following steps

1. download the sources from github
1. edit the package.xml file to update the version to 45
1. zip the whole folder you downloaded up
1. put the .zip up on a webserver (I put it behind IIS on my desktop)
1. update cumulus.yml as follows:
REMOVE the following line (you'll want to save a copy though for once this bug is fixed)
        - github: 'https://github.com/SalesforceFoundation/EASY-Open-Source-Solution'
ADD the following lines
        - zip_url: 'http://localhost:60/EASY.zip' 
          subfolder: 'EASY-Open-Source-Solution-master/src'
Of course you'll need to update the zip_url to point to wherever you have the .zip hosted (and of course match the name of your .zip file)
You'll also need to change the subfolder to point to the src folder inside your .zip.

**Comment by kyleschmid** [comment]
Thanks for the heads-up @nicolas-scarrci! Just updated the package version and pushed a new version of EASY with a couple of other bug fixes.
