### ISSUE TITLE
Deployment fails due to missing New Customer picklist value

### ISSUE THREAD

**Issue by brotheramai** [Kathy-Lueckeman/EASY-Open-Source-Solution#14]
A fresh install of EASY to a scratch org fails with the following error:
Update of RecordType Opportunity.Applicant_Opportunity: Error on line 292, col 18: Picklist value: New Customer in picklist: Type not found.

I think this is because the Application_Opportunity record type includes the value New Customer in the Type picklist, but /unpackaged/pre/opportunity_types/standardValueSets/OpportunityType.standardValueSet does not include this value.

**Comment by kyleschmid** [comment]
@nicolas-scarrci Thanks for pointing this out. Nothing has been updated since the package was originally configured for CCI. Just added this picklist value. Let me know if you still run into this issue.
