### ISSUE TITLE
Requirement_Response__c Missing fields

### ISSUE THREAD

**Issue by brotheramai** [Kathy-Lueckeman/EASY-Open-Source-Solution#17]
When attempting to install EASY I get the following error:

> Update of ApexClass ApplicationReview: Error on line 67, col 42: Question_Group_Requirement_Fulfilled_On__c, HasDocument__c, Waive_Requirement__c, Document_Requirement_Fulfilled_On__c
>                                                             ^
> ERROR at Row:1:Column:185
> No such column 'Waive_Requirement__c' on entity 'Requirement_Response__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please
> reference your WSDL or the describe call for the appropriate names.

It appears that references to new fields (e.g. Waive_Requirement__c) were added in version 1.44, but the Requirement_Response__c object was not updated as well.

**Comment by kyleschmid** [comment]
@nicolas-scarrci Thanks for the heads-up. It was included in the unmanaged package but I forgot to pull it down to the repo. Just added it. Let me know if you have any issues deploying.

**Comment by brotheramai** [comment]
2:07 AM! Ugh!
I tested this morning and everything built just fine. Thanks for the quick
response.

**Comment by kyleschmid** [comment]
Hey, it was only 1:07 AM CST. Glad it's working!
