### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by PacoPDS** [Kathy-Lueckeman/EASY-Open-Source-Solution#3]
On ant deploy to our Sandbox we are receiving the following errors on Code Coverage. Are there any workaround?
Code Coverage Failures:
1.  Class: ApplicationRegistration -- Test coverage of selected Apex Class is 65.979%, at least 75% test coverage is required
2.  Class: INT_InteractionProcessor -- Test coverage of selected Apex Class is 74.539%, at least 75% test coverage is required
3.  Class: ApplicationAdminView -- Test coverage of selected Apex Class is 74.312%, at least 75% test coverage is required
*********** DEPLOYMENT FAILED ***********

**Comment by kyleschmid** [comment]
@PacoPDS This has been fixed in our development environment. The next push (next week) will include a lot more coverage.

**Comment by kyleschmid** [comment]
Code coverage is now above 75% for all classes. The INT_InteractionProcessor class can't be fully covered in non-HEDA orgs because it first tests for HEDA before executing that part of the code.
