### ISSUE TITLE
INT_InteractionProcessor_TEST : testBulkInteractionInsert Failure

### ISSUE THREAD

**Issue by softwareangel** [Kathy-Lueckeman/EASY-Open-Source-Solution#7]
Greetings,

While running test classes in my developer org, I ran across some errors in the EASY test class suite related to running SELECT SQL queries in for loops, which generated the following error:

![image](https://user-images.githubusercontent.com/45464122/50050778-05633d00-00d3-11e9-9826-96641ae5bba2.png)

I took the time to fix some of the errors, but these coding examples that are cocontrary to Apex best practices may need to be addressed throughout the EASY code-base.

![image](https://user-images.githubusercontent.com/45464122/50050811-99350900-00d3-11e9-978e-9dadd1c2eb49.png)

I've attached the corrected Apex classes related to failed test:

[INT_InteractionProcessor_TEST.txt](https://github.com/SalesforceFoundation/EASY-Open-Source-Solution/files/2683315/INT_InteractionProcessor_TEST.txt)
[INT_InteractionMappingService.txt](https://github.com/SalesforceFoundation/EASY-Open-Source-Solution/files/2683316/INT_InteractionMappingService.txt)
[INT_InteractionProcessor.txt](https://github.com/SalesforceFoundation/EASY-Open-Source-Solution/files/2683317/INT_InteractionProcessor.txt)

**Comment by kyleschmid** [comment]
@softwareangel This is actually part of the codebase from the [Interactions for Student Recruitment](https://github.com/SFDO-Community/Interactions-for-Student-Recruitment) project. Can you submit this as an issue on their Github? I can update it in EASY once they make changes. Just trying to keep things in-sync.

**Comment by softwareangel** [comment]
Oh Wow.  I understand the need to keep everything organized.  I will
re-submit to them.
That sheds light on another suggestion: most unmanaged sources prefix
objects, classes and triggers with a notation as identitfiers. I would
suggest EASY_ and ISR (I assume they use an INT_ prefix).

Thanks.

**Comment by kyleschmid** [comment]
Sounds good. And yes, I agree on the prefixes. We should have done that from the beginning but it was an afterthought. Don't want to break existing implementations at this point, however.

**Comment by softwareangel** [comment]
This issue can be closed.
(1) I fixed the INT_InteractionProcessor_TEST errors.
(2) In my tailored version of EASY, the unmanaged sources, objects, classes and triggers were prefixed with a notations EASY_ and ISR (with the INT_ prefix).
